#Pipeline de Aristidev para CI
#https://www.youtube.com/watch?v=Zfaev5IOBmI
name: Android CI

on:
  #on: [push]
  #on: [pull_request]
  push:
    branches: ["main"]
  pull_request:
    branches: ["onlyPopularMovies"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          #cache: 'gradle'

#      - name: Grant execute permission for gradlew
#        #ejecutar en la terminal el siguiente comando para evitar agregar las lineas al ci: git update-index --chmod=+x ./gradlew o solo gradlew
#        run: chmod +x gradlew

#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2

      - name: Build APP
        run: ./gradlew assemble #./gradlew build --no-daemon