#Pipeline de Aristidev para CI
#https://www.youtube.com/watch?v=Zfaev5IOBmI
name: Android CI

on:
#  [push]
  #on: [pull_request]

#  push:
#    branches: ["onlyPopularMovies", "feature/new-stuff-to-ci"]
#  pull_request:
#    branches: ["onlyPopularMovies"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Setup JDK
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
#          cache: 'gradle' Se necesita especificar más cosas

#         #ejecutar en la terminal el siguiente comando para evitar agregar las lineas al ci:
#         #git update-index --chmod=+x ./gradlew o solo gradlew
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew

#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v3

      - name: Restore cache
        uses: actions/cache@v2
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          key: ${{ runner.os }}-gradle-${{ hashFiles('**/*.gradle*') }}
          restore-keys: |
            ${{ runner.os }}-gradle-
#
      - name: Assamble with Gradle
        run: ./gradlew assemble
#        run: ./gradlew build --no-daemon
