#Pipeline de Aristidev para CI
#https://www.youtube.com/watch?v=Zfaev5IOBmI
name: Android CI

on:
  #on: [push]
  #on: [pull_request]
  push:
    branches: ["main"]
  pull_request:
    branches: ["onlyPopularMovies"]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set Up JDK
        uses: actions/setup-java@v3
        with:
          #java-version: 1.8 sin distribution ni cache
          java-version: '17'
          distribution: 'temurin'
          #cache: 'gradle'

      #Define Android Build Tasks

      - name: Run Unit Test
        #run: ./gradlew test
        run: ./gradlew testValentinDebugUnitTest

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
        # This will always run the action even if the previous steps fails
        if: ${{ always() }}

      #- name: Grant execute permission for gradlew
        #ejecutar en la terminal el siguiente comando para evitar agregar las lineas al ci: git update-index --chmod=+x ./gradlew
       # run: chmod +x gradlew

      #- name: Setup Gradle
        #uses: gradle/gradle-build-action@v2

      - name: Build APP
        run: ./gradlew assemble #./gradlew build

      #- name: Build with Gradle
      #  run: ./gradlew build --no-daemon