
# https://www.youtube.com/watch?v=KYG8lXZCVr4&list=PLj0aVRF4hXSXP3NgNggHnfhDHx-yFbbu_&index=3&t=190s
name: Deploy to Firebase App Distribution

on:
  workflow_dispatch:
    inputs:
      release_notes:
        type: string
        required: true
        default: 'Manual Debug Build'
        description: 'Release notes for this build'


jobs:
  build:
    name: Building and distributing app
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

#      - name: Setup Gradle
#        uses: gradle/gradle-build-action@v2
#
#         #ejecutar en la terminal el siguiente comando para evitar agregar las lineas al ci:
#         #git update-index --chmod=+x ./gradlew o solo gradlew
#      - name: Grant execute permission for gradlew
#        run: chmod +x ./gradlew

      - name: Build APP
        run: ./gradlew assembleDebug
      #- name: build release
        #run: ./gradlew assembleRelease

      - name: Upload apk to Firebase App Distribution
        uses: wzieba/Firebase-Distribution-Github-Action@v1
        with:
          appId: ${{secrets.FIREBASE_APP_ID}}
          serviceCredentialsFileContent: ${{ secrets.CREDENTIAL_FILE_CONTENT }}
          groups: testers
          releaseNotes: ${{ github.event.inputs.release_notes }}
          #file: app/build/outputs/apk/release/app-release-unsigned.apk
          file: app/build/outputs/apk/dev/debug/app-dev-debug.apk







      - name: Upload APK Artifact
        uses: actions/upload-artifact@v2
        with:
          name: apk
          path: app/build/outputs/apk/dev/debug/app-dev-debug.apk
        run:  echo 'Artifact ID is ${{ steps.artifact-upload-step.outputs.artifact-id }}'

  distribute:

    needs: [ build ]
    runs-on: ubuntu-latest

    steps:
      - name: Download APK
        uses: actions/download-artifact@v2.0.5
        id: download
        with:
          name: app
          path: ./
      - name: Distribute to App Center
        uses: wzieba/AppCenter-Github-Action@v1.2.1
        with:
          appName: LearnProgrammingAcademy/My-Investments
          token: ${{secrets.APP_CENTER_TOKEN}}
          group: Beta Testers
          file: ${{steps.download.outputs.download-path}}/app-debug.apk
          notifyTesters: true