#Pipeline de Aristidev para CI
#https://www.youtube.com/watch?v=JYeYvEUq8Yw
name: Android Testing

on:
#  [push]
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup JDK
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'gradle'

#         #ejecutar en la terminal el siguiente comando para evitar agregar las lineas al ci:
#         #git update-index --chmod=+x ./gradlew o solo gradlew
#      - name: Grant execute permission for gradlew
#        run: chmod +x gradlew

#       Run UI Test
      - name: Run Debug Tests
        run: ./gradlew testDevDebugUnitTest

#     Run Debug ktlint
#      - name: Run Debug ktlint
#        run: ./gradlew ktlintDevDebugCheck

      - name: Run Debug Lint
        run: ./gradlew lintDevDebug

      - name: Android Test Report
        uses: asadmansr/android-test-report-action@v1.2.0
#       This will always run the action even if the previous steps fails
        if: ${{ always() }}

      - name: Upload Test Results as Artifacts
        if: ${{ always() }}
        uses: actions/upload-artifact@v2
        with:
          name: test-reports
          path: '**/build/reports/tests/'
